//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "name")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub owner: String,
    pub original_owner: Option<String>,
    pub registered: DateTime,
    pub updated: Option<DateTime>,
    pub transferred: Option<DateTime>,
    pub metadata: Option<String>,
    #[sea_orm(column_type = "Float")]
    pub unpaid: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
